// Code generated by goctl. DO NOT EDIT.
package types

type GetShortRequest struct {
	Code string `path:"code"`
}

type CreateRequest struct {
	DataType          string `json:"dataType,options=url|data"`
	ProhibitEffective bool   `json:"prohibitEffective,optional"`
	Data              string `json:"data"`
	ExprieInMinutes   int64  `json:"expireInMinutes,optional"` // -1 表示永久
	ExprieTime        string `json:"exprieTime,optional"`      // ExprieTime 存在ExprieInMinutes 不生效
	CreateBy          string `json:"createBy,optional"`
}

type UpdateRequest struct {
	Code string `json:"code"`
	CreateRequest
	Status int `json:"status,options=1|2|3"` // 1 正常 2 禁用 3 删除
}

type GetListRequest struct {
	Page      int    `form:"page"`
	PageSize  int    `form:"pageSize"`
	CreateBy  string `form:"createBy,optional"`
	DataType  string `form:"dataType,options=url|data"`
	Permanent bool   `form:"permanent,optional"`
	ShortCode string `form:"shortCode,optional"`
}

type Response struct {
	Code int64       `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}
