// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	shorturl "shorturl/internal/handler/shorturl"
	"shorturl/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/getUrl/:code",
				Handler: shorturl.GetShorturlHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: shorturl.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: shorturl.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getList",
				Handler: shorturl.GetListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getData/:code",
				Handler: shorturl.GetDataHandler(serverCtx),
			},
		},
		rest.WithPrefix("/shorturl"),
	)
}
